version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-react-flowbite-container
    image: dockerized-react-flowbite
    ports:
      - "5173:80"
    volumes:
      - .:/app
